insert into content values (1, 2003, true, true, 'US', 180000, 2008, 'Breaking Bad', 'SERIE');
insert into content values (2, 1997, true, true, 'US', 120, 1997, 'Scream', 'MOVIE');
insert into content values (3, 2011, true, true, 'US', 90000, 2019, 'Game of 766', 'SERIE');
insert into content values (4,2009,true,true,'UG',9000,2000,'Manhattan Murder Myster', 'MOVIE');
insert into content values (5,1985,true,false,'CN',9000,2005,'Kiss Me, Stupid', 'MOVIE');
insert into content values (6,2006,true,true,'ID',9000,2009,'Armed and Dangerous', 'MOVIE');
insert into content values (7,1994,false,false,'PH',9000,2000,'If You Dont Stop It... Youll Go Blin', 'MOVIE');
insert into content values (8,1981,false,false,'RU',9000,2007,'Great Ecstasy of Robert Carmichael, Th', 'MOVIE');
insert into content values (9,2009,true,false,'VN',9000,1987,'Too Early, Too Late (Trop tôt, trop tard)', 'MOVIE');
insert into content values (10,2006,false,true,'PL',9000,2007,'Last Time I Saw Archie, Th', 'MOVIE');
insert into content values (11,2002,false,false,'ID',9000,2009,'Big Wednesda', 'MOVIE');
insert into content values (12,2004,false,false,'AD',9000,2005,'Hands Off the Loot (Touchez pas au grisbi)', 'MOVIE');
insert into content values (13,2001,true,false,'YE',9000,2007,'Secrets of Jonathan Sperry, Th', 'MOVIE');
insert into content values (14,1993,true,false,'ZA',9000,2012,'Balanc', 'MOVIE');
insert into content values (15,2004,true,true,'CN',9000,2012,'Take Aim at the Police Van (Sono gosôsha wo nerae: Jûsangô taihisen yori)', 'MOVIE');
insert into content values (16,1998,true,false,'AL',9000,1992,'Rock-A-Doodl', 'MOVIE');
insert into content values (17,1992,false,true,'PE',9000,1983,'Barabba', 'MOVIE');
insert into content values (18,2001,true,false,'CN',9000,1997,'Maria (Mariya)', 'MOVIE');
insert into content values (19,2004,false,false,'TZ',9000,1985,'Batma', 'MOVIE');
insert into content values (20,2011,false,true,'PH',9000,2011,'Ragamuffi', 'MOVIE');
insert into content values (21,2008,true,true,'RU',9000,2009,'Hit Squad', 'MOVIE');
insert into content values (22,1995,false,false,'ID',9000,2009,'Jane Austen Book Club, Th', 'MOVIE');
insert into content values (23,2010,false,false,'GM',9000,2012,'X2: X-Men Unite', 'MOVIE');
insert into content values (24,2009,false,false,'TH',9000,2009,'Drinking Buddies', 'MOVIE');
insert into content values (25,2006,true,true,'CN',9000,1989,'Street Without End (Kagirinaki hod)', 'MOVIE');
insert into content values (26,2006,true,true,'ID',9000,1998,'My Best Friends Weddin', 'MOVIE');
insert into content values (27,2009,true,false,'TH',9000,1993,'Reminiscences of a Journey to Lithuani', 'MOVIE');
insert into content values (28,2006,false,false,'PH',9000,2012,'Dark Skies', 'MOVIE');
insert into content values (29,2006,false,false,'ID',9000,2012,'Everybodys Got Somebody... Not M', 'MOVIE');
insert into content values (30,2009,true,false,'ID',9000,2001,'The Trial of Lee Harvey Oswald', 'MOVIE');
insert into content values (31,2010,true,true,'CO',9000,1995,'At the River I Stan', 'MOVIE');
insert into content values (32,2004,true,true,'RU',9000,1991,'Flashbacks of a Foo', 'MOVIE');
insert into content values (33,1992,false,true,'SE',9000,1999,'Mercenary for Justice', 'MOVIE');
insert into content values (34,2004,false,false,'CN',9000,1964,'Secretaria', 'MOVIE');
insert into content values (35,2011,true,false,'CN',9000,2003,'Cowboys, Th', 'MOVIE');
insert into content values (36,2006,false,false,'PT',9000,2004,'Enders Game', 'MOVIE');
insert into content values (37,2006,true,true,'BT',9000,2007,'Love Is a Woman (Death Is a Woman)', 'MOVIE');
insert into content values (38,1996,true,true,'CN',9000,2006,'God Is the Bigger Elvi', 'MOVIE');
insert into content values (39,1992,true,true,'CN',9000,1984,'Odd Thomas', 'MOVIE');
insert into content values (40,2008,false,true,'SZ',9000,2004,'2 Days in the Valle', 'MOVIE');
insert into content values (41,2004,true,true,'GT',9000,2006,'French Connection, Th', 'MOVIE');
insert into content values (42,1992,true,false,'SE',9000,2007,'Hoop Dreams', 'MOVIE');
insert into content values (43,1992,true,true,'CN',9000,1963,'The Case of the Curious Brid', 'MOVIE');
insert into content values (44,2002,false,true,'CN',9000,1987,'Zindagi Na Milegi Dobar', 'MOVIE');
insert into content values (45,1992,true,true,'ID',9000,1994,'Attack Force', 'MOVIE');
insert into content values (46,2007,false,true,'IR',9000,2009,'Welcome to Sherwood! The Story of The Adventures of Robin Hoo', 'MOVIE');
insert into content values (47,2008,false,true,'BY',9000,2009,'Prefontain', 'MOVIE');
insert into content values (48,2004,false,false,'ID',9000,1969,'Tito and Me (Tito i ja)', 'MOVIE');
insert into content values (49,1992,true,true,'PE',9000,2010,'Pleasure Seekers, Th', 'MOVIE');
insert into content values (50,2002,true,true,'ID',9000,2010,'Familie, E', 'MOVIE');
insert into content values (51,1998,true,true,'CN',9000,2010,'Recoil', 'MOVIE');
insert into content values (52,2000,true,false,'CO',9000,2003,'Rhythm of a Crime (Ritam zlocin)', 'MOVIE');
insert into content values (53,2002,true,false,'SE',9000,2007,'Map For Saturday, ', 'MOVIE');
insert into content values (54,1998,false,false,'ID',9000,2004,'Black Rain (Kuroi ame)', 'MOVIE');
insert into content values (55,2011,true,false,'CN',9000,2008,'Shockproo', 'MOVIE');
insert into content values (56,1988,true,true,'RU',9000,2004,'Film ist', 'MOVIE');
insert into content values (57,1986,true,true,'CO',9000,2011,'Assassination of Jesse James by the Coward Robert Ford, The', 'MOVIE');
insert into content values (58,1998,false,false,'BA',9000,1994,'Walk in the Clouds, ', 'MOVIE');
insert into content values (59,2007,false,false,'RS',9000,1998,'Boy Named Charlie Brown, ', 'MOVIE');
insert into content values (60,2010,false,false,'RU',9000,2011,'Scarlet Letter, The', 'MOVIE');
insert into content values (61,1995,true,true,'SY',9000,2006,'Kingdom, The (Rige)', 'MOVIE');
insert into content values (62,2002,true,false,'ML',9000,1992,'Roma', 'MOVIE');
insert into content values (63,1996,true,true,'SN',9000,2000,'Kink', 'MOVIE');
insert into content values (64,1995,false,false,'BR',9000,1987,'Zenit', 'MOVIE');
insert into content values (65,1993,true,true,'MP',9000,1993,'Laggie', 'MOVIE');
insert into content values (66,2006,true,true,'NO',9000,2009,'Death In Love', 'MOVIE');
insert into content values (67,1994,true,true,'CN',9000,1997,'Getting I', 'MOVIE');
insert into content values (68,2011,true,false,'FR',9000,1995,'Whatever Lola Want', 'MOVIE');
insert into content values (69,2010,true,false,'CN',9000,2007,'Seeking a Friend for the End of the World', 'MOVIE');
insert into content values (70,2007,false,false,'VE',9000,2010,'Maximum Overdrive', 'MOVIE');
insert into content values (71,1988,true,false,'CN',9000,2003,'Dumb & Dumber (Dumb and Dumber', 'MOVIE');
insert into content values (72,2011,true,false,'CN',9000,1970,'The Widow From Chicago', 'MOVIE');
insert into content values (73,2000,false,false,'MX',9000,1993,'Postman Blue', 'MOVIE');
insert into content values (74,1987,true,false,'ID',9000,1990,'Belles on Their Toe', 'MOVIE');
insert into content values (75,1992,true,true,'PE',9000,1996,'Embodiment of Evil (Encarnação do Demônio)', 'MOVIE');
insert into content values (77,2008,false,false,'TN',9000,1989,'Oscar and the Lady in Pin', 'MOVIE');
insert into content values (78,2001,false,false,'MX',9000,1994,'Enthusiasm (Entuziazm: Simfoniya Donbassa)', 'MOVIE');
insert into content values (79,1999,true,false,'UA',9000,2011,'Bright Young Thing', 'MOVIE');
insert into content values (80,2007,true,false,'CN',9000,1986,'Conversation, Th', 'MOVIE');
insert into content values (81,1971,true,true,'US',9000,1994,'Cruel Story of Youth (Seishun zankoku monogatari)', 'MOVIE');
insert into content values (82,1987,true,false,'CN',9000,2006,'Slive', 'MOVIE');
insert into content values (83,2000,false,false,'NL',9000,1995,'Rat Race', 'MOVIE');
insert into content values (84,1968,true,false,'RU',9000,1996,'Désir', 'MOVIE');
insert into content values (85,2012,true,false,'TH',9000,2012,'Funhouse, The', 'MOVIE');
insert into content values (86,2003,false,true,'CA',9000,1997,'Oklahom', 'MOVIE');
insert into content values (87,1992,false,false,'JO',9000,2012,'The White Siste', 'MOVIE');
insert into content values (88,2002,true,false,'BR',9000,1998,'Visitor to a Museum (Posetitel muzeya)', 'MOVIE');
insert into content values (89,1998,true,true,'UA',9000,2008,'As Tears Go By (Wong gok ka moo)', 'MOVIE');
insert into content values (90,1993,false,false,'GE',9000,1994,'Gold Diggers of 193', 'MOVIE');
insert into content values (91,1998,true,true,'CN',9000,2010,'When the Game Stands Tall', 'MOVIE');
insert into content values (92,2001,false,false,'FR',9000,1996,'Shout, Th', 'MOVIE');
insert into content values (93,2002,false,true,'RU',9000,1996,'Vampire Hunter D: Bloodlust (Banpaia hantâ D', 'MOVIE');
insert into content values (94,2000,true,false,'BR',9000,1994,'Linda Linda Linda', 'MOVIE');
insert into content values (95,2006,true,false,'CN',9000,1992,'Big Man Japan (Dai-Nihonji', 'MOVIE');
insert into content values (96,1985,false,true,'JP',9000,1975,'Bad Luck (Zezowate szczescie', 'MOVIE');
insert into content values (97,1991,true,true,'PT',9000,2002,'Coherence', 'MOVIE');
insert into content values (98,2011,true,false,'PL',9000,1989,'Sta', 'MOVIE');
insert into content values (99,1997,true,true,'CN',9000,1999,'Zero Effec', 'MOVIE');
insert into content values (100,2008,false,false,'GQ',9000,2005,'Lisa', 'MOVIE');


insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (2,'Japan','Finnish', 'platform',5,true,52,93);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (3,'Peru','Afrikaans', 'platform',1,false,32,96);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (4,'Poland','Kazakh', 'platform',2,true,10,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (5,'Burkina Faso','Tami', 'platform' ,5,true,4,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (6,'Colombia','Telugu', 'platform',3,true,24,28);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (7,'Taiwan', 'Spanish', 'platform',3,true,95,51);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (8,'Moldova','Papiamento', 'platform',3,true,11,44);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (9,'Greece','Māori', 'platform',2,true,26,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (10,'United States','Māor', 'platform',5,false,93,44);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (11,'China','Sotho', 'platform',3,false,37,84);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (12,'Portugal','Hebrew', 'platform',5,true,64,27);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (13,'China','Azeri', 'platform',5,false,14,83);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (14,'Pakistan','Malagasy', 'platform',1,true,21,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (15,'Russia','Swati', 'platform',1,false,93,61);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (16,'Tanzania','Catalan', 'platform',5,true,92,77);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (17,'Canada','Tamil', 'platform',4,false,44,23);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (18,'Poland','Dari', 'platform',5,true,21,30);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (19,'China','Irish', 'platform',4,true,42,75);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (20,'Brazil','Nepali', 'platform',2,false,14,88);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (21,'Indonesia','Danish', 'platform',5,true,39,87);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (22,'Tajikistan','Lao', 'platform',3,false,78,90);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (23,'Indonesia','Dhivehi', 'platform',3,true,39,12);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (24,'United States', 'Punjab', 'platform',5,false,39,17);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (25,'Jamaica','Spanish', 'platform',2,true,18,56);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (26,'Thailand','Kazakh', 'platform',4,true,58,42);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (27,'Japan','Spanish', 'platform',5,false,12,58);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (28,'China','Somali', 'platform',2,true,28,78);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (29,'Japan','Indonesian', 'platform',3,false,1,97);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (30,'Indonesia','Azeri', 'platform',2,true,44,19);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (31,'Sweden','Guaraní', 'platform',1,true,44,63);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (32,'China','Icelandic', 'platform',5,false,54,7);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (33,'China','Bosnian', 'platform',3,false,59,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (34,'South Africa','Haitian Creol', 'platform ',5,false,18,63);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (35,'Thailand','Spanish' , 'platform',4,true,72,73);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (36,'United States','Tswan', 'platform',1,false,56,89);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (37,'Russia','Danish', 'platform',2,true,32,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (38,'China','Bislama', 'platform',1,false,42,31);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (39,'Burkina Faso','Latvia', 'platform' ,5,false,9,86);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (40,'Indonesia','Tetum', 'platform',2,false,48,30);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (41,'China','Lao', 'platform',3,false,60,72);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (42,'Brazil','Hungarian', 'platform',4,true,24,29);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (43,'Malaysia','Maltese', 'platform',3,true,73,53);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (44,'Slovenia','Assamese', 'platform',3,false,16,10);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (45,'Portugal','Bulgarian', 'platform',1,true,26,48);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (46,'United States','Latvia', 'platform',1,false,56,9);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (47,'Russia','Spanish', 'platform',2,true,81,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (48,'Yemen','Pashto', 'platform',5,false,60,18);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (49,'Philippines','Pashto', 'platform',3,true,17,56);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (50,'South Korea','Moldova', 'platform' ,3,true,98,3);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (51,'China','Danish', 'platform',3,true,69,40);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (52,'Russia','Khmer', 'platform',3,false,36,12);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (53,'Canada','Marathi', 'platform',1,true,66,12);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (54,'Indonesia','Malagasy', 'platform',5,true,67,71);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (55,'Philippines','Telugu', 'platform',4,false,52,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (56,'Thailand','Bosnian', 'platform',2,true,23,94);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (57,'Bulgaria','Gagauz', 'platform',4,true,84,43);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (58,'Cambodia','Pashto', 'platform',2,false,73,59);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (59,'Brazil','Papiamento', 'platform',3,true,50,78);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (60,'Kiribati','Sotho', 'platform',2,true,34,24);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (61,'Indonesia','Dzongkha', 'platform',3,false,34,92);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (62,'Indonesia','Guaraní', 'platform',5,false,67,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (63,'Peru','French', 'platform',2,true,38,52);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (64,'France','Zulu', 'platform',3,true,34,27);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (65,'Indonesia','Afrikaans', 'platform',1,false,44,69);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (66,'Indonesia','Maltese', 'platform',5,false,22,97);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (67,'China','Spanish', 'platform',5,false,21,38);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (68,'China','Kyrgyz', 'platform',3,false,36,36);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (69,'Vietnam','Pashto', 'platform',3,false,50,15);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (70,'Portugal','Malay', 'platform',5,true,14,73);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (71,'Brazil','Danish', 'platform',3,true,73,24);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (72,'China','Nepali', 'platform',1,false,26,72);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (73,'China','Tswana', 'platform',5,false,16,3);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (74,'Croatia','Malay', 'platform',2,true,77,57);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (75,'Thailand','Latvian', 'platform',4,true,46,40);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (76,'China','Hebrew', 'platform',3,false,84,74);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (77,'Kazakhstan','Dari', 'platform',5,false,69,30);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (78,'Germany','Croatian', 'platform',4,false,48,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (79,'Panama','Tamil', 'platform',5,true,65,30);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (80,'Honduras','Hebrew', 'platform',2,false,25,8);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (81,'China','German', 'platform',1,true,20,76);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (82,'Vietnam','Dari', 'platform',1,true,60,74);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (83,'China', 'Spanish', 'platform',1,false,34,52);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (84,'Poland','Afrikaans', 'platform',2,false,55,3);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (85,'Indonesia','Spanish', 'platform',2,true,46,19);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (86,'Greece','Chinese', 'platform',2,false,40,80);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (87,'Philippines','Thai', 'platform',1,true,92,13);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (88,'Canada','Bulgarian', 'platform',1,true,100,42);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (89,'Albania', 'Latvia', 'platform',4,true,11,43);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (90,'Cameroon','Luxembourgish', 'platform',5,true,98,51);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (91,'Indonesia','Albanian', 'platform',5,false,29,74);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (92,'Honduras','Italian', 'platform',1,false,8,84);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (93,'Morocco','Tetum', 'platform',2,false,84,56);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (94,'Syria','Hebrew', 'platform',1,false,26,87);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (95,'Tajikistan','Sotho', 'platform',5,true,46,3);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (96,'Philippines','Portuguese', 'platform',1,true,77,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (97,'Thailand','Telugu', 'platform',1,true,22,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes) values (98,'China','Thai', 'platform',4,false,34,56);



-- insert into review (id,likes,dislikes,spoiler_alert,content_id,rating) values (2,1,1,false,1,1);

-- insert into review (id,likes,dislikes,spoiler_alert,content_id,rating) values (1,1,1,false,1,5);
--data fake temporal para probar busqueda de reviews con filtros
--
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date, content_id) values (1,'arg', 'spanish','netflix',5,false,1,1,'2011-02-12',1);
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date, content_id) values (2,'arg', 'english','netflix',4,false,1,1,'2010-03-12',1);
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (3,'chl', 'spanish','netflix',2,false,1,1,'2009-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (5,'arg', 'spanish','netflix',5,false,1,1,'2011-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (6,'arg', 'english','netflix',1,false,1,1,'2011-03-11');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (4,'arg', 'spanish','amazon',3,false,1,1,'2011-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (7,'chl', 'spanish','netflix',3,false,1,1,'2011-01-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (8,'arg', 'spanish','amazon',1,false,1,1,'2004-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (9,'arg', 'spanish','netflix',5,false,1,1,'2002-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (10,'arg', 'english','netflix',3,false,1,1,'1990-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (11,'chl', 'spanish','netflix',2,false,1,1,'2011-03-12');
--insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, date) values (12,'arg', 'spanish','amazon',4,false,1,1,'2011-02-10');