insert into content values (1, 2003, true, true, 'US', 180000, 2008, 'Breaking Bad', 'SERIE');
insert into content values (2, 1997, true, true, 'US', 120, 1997, 'Scream', 'MOVIE');
insert into content values (3, 2011, true, true, 'US', 90000, 2019, 'Game of 766', 'SERIE');
insert into content values (4,2009,true,true,'UG',9000,2000,'Manhattan Murder Myster', 'MOVIE');
insert into content values (5,1985,true,false,'CN',9000,2005,'Kiss Me, Stupid', 'MOVIE');
insert into content values (6,2006,true,true,'ID',9000,2009,'Armed and Dangerous', 'MOVIE');
insert into content values (7,1994,false,false,'PH',9000,2000,'If You Dont Stop It... Youll Go Blin', 'MOVIE');
insert into content values (8,1981,false,false,'RU',9000,2007,'Great Ecstasy of Robert Carmichael, Th', 'MOVIE');
insert into content values (9,2009,true,false,'VN',9000,1987,'Too Early, Too Late (Trop tôt, trop tard)', 'MOVIE');
insert into content values (10,2006,false,true,'PL',9000,2007,'Last Time I Saw Archie, Th', 'MOVIE');
insert into content values (11,2002,false,false,'ID',9000,2009,'Big Wednesda', 'MOVIE');
insert into content values (12,2004,false,false,'AD',9000,2005,'Hands Off the Loot (Touchez pas au grisbi)', 'MOVIE');
insert into content values (13,2001,true,false,'YE',9000,2007,'Secrets of Jonathan Sperry, Th', 'MOVIE');
insert into content values (14,1993,true,false,'ZA',9000,2012,'Balanc', 'MOVIE');
insert into content values (15,2004,true,true,'CN',9000,2012,'Take Aim at the Police Van (Sono gosôsha wo nerae: Jûsangô taihisen yori)', 'MOVIE');
insert into content values (16,1998,true,false,'AL',9000,1992,'Rock-A-Doodl', 'MOVIE');
insert into content values (17,1992,false,true,'PE',9000,1983,'Barabba', 'MOVIE');
insert into content values (18,2001,true,false,'CN',9000,1997,'Maria (Mariya)', 'MOVIE');
insert into content values (19,2004,false,false,'TZ',9000,1985,'Batma', 'MOVIE');
insert into content values (20,2011,false,true,'PH',9000,2011,'Ragamuffi', 'MOVIE');
insert into content values (21,2008,true,true,'RU',9000,2009,'Hit Squad', 'MOVIE');
insert into content values (22,1995,false,false,'ID',9000,2009,'Jane Austen Book Club, Th', 'MOVIE');
insert into content values (23,2010,false,false,'GM',9000,2012,'X2: X-Men Unite', 'MOVIE');
insert into content values (24,2009,false,false,'TH',9000,2009,'Drinking Buddies', 'MOVIE');
insert into content values (25,2006,true,true,'CN',9000,1989,'Street Without End (Kagirinaki hod)', 'MOVIE');
insert into content values (26,2006,true,true,'ID',9000,1998,'My Best Friends Weddin', 'MOVIE');
insert into content values (27,2009,true,false,'TH',9000,1993,'Reminiscences of a Journey to Lithuani', 'MOVIE');
insert into content values (28,2006,false,false,'PH',9000,2012,'Dark Skies', 'MOVIE');
insert into content values (29,2006,false,false,'ID',9000,2012,'Everybodys Got Somebody... Not M', 'MOVIE');
insert into content values (30,2009,true,false,'ID',9000,2001,'The Trial of Lee Harvey Oswald', 'MOVIE');
insert into content values (31,2010,true,true,'CO',9000,1995,'At the River I Stan', 'MOVIE');
insert into content values (32,2004,true,true,'RU',9000,1991,'Flashbacks of a Foo', 'MOVIE');
insert into content values (33,1992,false,true,'SE',9000,1999,'Mercenary for Justice', 'MOVIE');
insert into content values (34,2004,false,false,'CN',9000,1964,'Secretaria', 'MOVIE');
insert into content values (35,2011,true,false,'CN',9000,2003,'Cowboys, Th', 'MOVIE');
insert into content values (36,2006,false,false,'PT',9000,2004,'Enders Game', 'MOVIE');
insert into content values (37,2006,true,true,'BT',9000,2007,'Love Is a Woman (Death Is a Woman)', 'MOVIE');
insert into content values (38,1996,true,true,'CN',9000,2006,'God Is the Bigger Elvi', 'MOVIE');
insert into content values (39,1992,true,true,'CN',9000,1984,'Odd Thomas', 'MOVIE');
insert into content values (40,2008,false,true,'SZ',9000,2004,'2 Days in the Valle', 'MOVIE');
insert into content values (41,2004,true,true,'GT',9000,2006,'French Connection, Th', 'MOVIE');
insert into content values (42,1992,true,false,'SE',9000,2007,'Hoop Dreams', 'MOVIE');
insert into content values (43,1992,true,true,'CN',9000,1963,'The Case of the Curious Brid', 'MOVIE');
insert into content values (44,2002,false,true,'CN',9000,1987,'Zindagi Na Milegi Dobar', 'MOVIE');
insert into content values (45,1992,true,true,'ID',9000,1994,'Attack Force', 'MOVIE');
insert into content values (46,2007,false,true,'IR',9000,2009,'Welcome to Sherwood! The Story of The Adventures of Robin Hoo', 'MOVIE');
insert into content values (47,2008,false,true,'BY',9000,2009,'Prefontain', 'MOVIE');
insert into content values (48,2004,false,false,'ID',9000,1969,'Tito and Me (Tito i ja)', 'MOVIE');
insert into content values (49,1992,true,true,'PE',9000,2010,'Pleasure Seekers, Th', 'MOVIE');
insert into content values (50,2002,true,true,'ID',9000,2010,'Familie, E', 'MOVIE');
insert into content values (51,1998,true,true,'CN',9000,2010,'Recoil', 'MOVIE');
insert into content values (52,2000,true,false,'CO',9000,2003,'Rhythm of a Crime (Ritam zlocin)', 'MOVIE');
insert into content values (53,2002,true,false,'SE',9000,2007,'Map For Saturday, ', 'MOVIE');
insert into content values (54,1998,false,false,'ID',9000,2004,'Black Rain (Kuroi ame)', 'MOVIE');
insert into content values (55,2011,true,false,'CN',9000,2008,'Shockproo', 'MOVIE');
insert into content values (56,1988,true,true,'RU',9000,2004,'Film ist', 'MOVIE');
insert into content values (57,1986,true,true,'CO',9000,2011,'Assassination of Jesse James by the Coward Robert Ford, The', 'MOVIE');
insert into content values (58,1998,false,false,'BA',9000,1994,'Walk in the Clouds, ', 'MOVIE');
insert into content values (59,2007,false,false,'RS',9000,1998,'Boy Named Charlie Brown, ', 'MOVIE');
insert into content values (60,2010,false,false,'RU',9000,2011,'Scarlet Letter, The', 'MOVIE');
insert into content values (61,1995,true,true,'SY',9000,2006,'Kingdom, The (Rige)', 'MOVIE');
insert into content values (62,2002,true,false,'ML',9000,1992,'Roma', 'MOVIE');
insert into content values (63,1996,true,true,'SN',9000,2000,'Kink', 'MOVIE');
insert into content values (64,1995,false,false,'BR',9000,1987,'Zenit', 'MOVIE');
insert into content values (65,1993,true,true,'MP',9000,1993,'Laggie', 'MOVIE');
insert into content values (66,2006,true,true,'NO',9000,2009,'Death In Love', 'MOVIE');
insert into content values (67,1994,true,true,'CN',9000,1997,'Getting I', 'MOVIE');
insert into content values (68,2011,true,false,'FR',9000,1995,'Whatever Lola Want', 'MOVIE');
insert into content values (69,2010,true,false,'CN',9000,2007,'Seeking a Friend for the End of the World', 'MOVIE');
insert into content values (70,2007,false,false,'VE',9000,2010,'Maximum Overdrive', 'MOVIE');
insert into content values (71,1988,true,false,'CN',9000,2003,'Dumb & Dumber (Dumb and Dumber', 'MOVIE');
insert into content values (72,2011,true,false,'CN',9000,1970,'The Widow From Chicago', 'MOVIE');
insert into content values (73,2000,false,false,'MX',9000,1993,'Postman Blue', 'MOVIE');
insert into content values (74,1987,true,false,'ID',9000,1990,'Belles on Their Toe', 'MOVIE');
insert into content values (75,1992,true,true,'PE',9000,1996,'Embodiment of Evil (Encarnação do Demônio)', 'MOVIE');
insert into content values (77,2008,false,false,'TN',9000,1989,'Oscar and the Lady in Pin', 'MOVIE');
insert into content values (78,2001,false,false,'MX',9000,1994,'Enthusiasm (Entuziazm: Simfoniya Donbassa)', 'MOVIE');
insert into content values (79,1999,true,false,'UA',9000,2011,'Bright Young Thing', 'MOVIE');
insert into content values (80,2007,true,false,'CN',9000,1986,'Conversation, Th', 'MOVIE');
insert into content values (81,1971,true,true,'US',9000,1994,'Cruel Story of Youth (Seishun zankoku monogatari)', 'MOVIE');
insert into content values (82,1987,true,false,'CN',9000,2006,'Slive', 'MOVIE');
insert into content values (83,2000,false,false,'NL',9000,1995,'Rat Race', 'MOVIE');
insert into content values (84,1968,true,false,'RU',9000,1996,'Désir', 'MOVIE');
insert into content values (85,2012,true,false,'TH',9000,2012,'Funhouse, The', 'MOVIE');
insert into content values (86,2003,false,true,'CA',9000,1997,'Oklahom', 'MOVIE');
insert into content values (87,1992,false,false,'JO',9000,2012,'The White Siste', 'MOVIE');
insert into content values (88,2002,true,false,'BR',9000,1998,'Visitor to a Museum (Posetitel muzeya)', 'MOVIE');
insert into content values (89,1998,true,true,'UA',9000,2008,'As Tears Go By (Wong gok ka moo)', 'MOVIE');
insert into content values (90,1993,false,false,'GE',9000,1994,'Gold Diggers of 193', 'MOVIE');
insert into content values (91,1998,true,true,'CN',9000,2010,'When the Game Stands Tall', 'MOVIE');
insert into content values (92,2001,false,false,'FR',9000,1996,'Shout, Th', 'MOVIE');
insert into content values (93,2002,false,true,'RU',9000,1996,'Vampire Hunter D: Bloodlust (Banpaia hantâ D', 'MOVIE');
insert into content values (94,2000,true,false,'BR',9000,1994,'Linda Linda Linda', 'MOVIE');
insert into content values (95,2006,true,false,'CN',9000,1992,'Big Man Japan (Dai-Nihonji', 'MOVIE');
insert into content values (96,1985,false,true,'JP',9000,1975,'Bad Luck (Zezowate szczescie', 'MOVIE');
insert into content values (97,1991,true,true,'PT',9000,2002,'Coherence', 'MOVIE');
insert into content values (98,2011,true,false,'PL',9000,1989,'Sta', 'MOVIE');
insert into content values (99,1997,true,true,'CN',9000,1999,'Zero Effec', 'MOVIE');
insert into content values (100,2008,false,false,'GQ',9000,2005,'Lisa', 'MOVIE');


insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (2,'Japan','Finnish', 'Netflix',5,true,52,93,1);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (3,'Peru','Afrikaans', 'Netflix',1,false,32,96,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (4,'Poland','Kazakh', 'Netflix',2,true,10,1,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (5,'Burkina Faso','Tami', 'Netflix' ,5,true,4,5,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (6,'Colombia','Telugu', 'Netflix',3,true,24,28,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (7,'Taiwan', 'Spanish', 'Netflix',3,true,95,51,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (8,'Moldova','Papiamento', 'Netflix',3,true,11,44,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (9,'Greece','Māori', 'Netflix',2,true,26,25,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (10,'United States','Māor', 'Netflix',5,false,93,44,2);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (11,'China','Sotho', 'Netflix',3,false,37,84,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (12,'Portugal','Hebrew', 'Netflix',5,true,64,27,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (13,'China','Azeri', 'Amazon',5,false,14,83,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (14,'Pakistan','Malagasy', 'Amazon',1,true,21,66,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (15,'Russia','Swati', 'Amazon',1,false,93,61,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (16,'Tanzania','Catalan', 'Amazon',5,true,92,77,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (17,'Canada','Tamil', 'Amazon',4,false,44,23,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (18,'Poland','Dari', 'Amazon',5,true,21,30,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (19,'China','Irish', 'Amazon',4,true,42,75,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (20,'Brazil','Nepali', 'Amazon',2,false,14,88,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (21,'Indonesia','Danish', 'Amazon',5,true,39,87,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (22,'Tajikistan','Lao', 'Amazon',3,false,78,90,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (23,'Indonesia','Dhivehi', 'Amazon',3,true,39,12,14);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (24,'United States', 'Punjab', 'Amazon',5,false,39,17,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (25,'Jamaica','Spanish', 'Amazon',2,true,18,56,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (26,'Thailand','Kazakh', 'Amazon',4,true,58,42,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (27,'Japan','Spanish', 'Amazon',5,false,12,58,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (28,'China','Somali', 'Disney+',2,true,28,78,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (29,'Japan','Indonesian', 'Disney+',3,false,1,97,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (30,'Indonesia','Azeri', 'Disney+',2,true,44,19,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (31,'Sweden','Guaraní', 'Disney+',1,true,44,63,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (32,'China','Icelandic', 'Disney+',5,false,54,7,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (33,'China','Bosnian', 'Disney+',3,false,59,2,4);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (34,'South Africa','Haitian Creol', 'platform ',5,false,18,63,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (35,'Thailand','Spanish' , 'Disney+',4,true,72,73,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (36,'United States','Tswan', 'Disney+',1,false,56,89,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (37,'Russia','Danish', 'Disney+',2,true,32,4,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (38,'China','Bislama', 'Disney+',1,false,42,31,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (39,'Burkina Faso','Latvia', 'Disney+' ,5,false,9,86,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (40,'Indonesia','Tetum', 'Disney+',2,false,48,30,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (41,'China','Lao', 'Disney+',3,false,60,72,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (42,'Brazil','Hungarian', 'Disney+',4,true,24,29,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (43,'Malaysia','Maltese', 'Disney+',3,true,73,53,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (44,'Slovenia','Assamese', 'Disney+',3,false,16,10,5);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (45,'Portugal','Bulgarian', 'Disney+',1,true,26,48,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (46,'United States','Latvia', 'Disney+',1,false,56,9,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (47,'Russia','Spanish', 'Disney+',2,true,81,1,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (48,'Yemen','Pashto', 'Disney+',5,false,60,18,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (49,'Philippines','Pashto', 'Disney+',3,true,17,56,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (50,'South Korea','Moldova', 'Disney+' ,3,true,98,3,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (51,'China','Danish', 'Disney+',3,true,69,40,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (52,'Russia','Khmer', 'Disney+',3,false,36,12,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (53,'Canada','Marathi', 'Disney+',1,true,66,12,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (54,'Indonesia','Malagasy', 'Disney+',5,true,67,71,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (55,'Philippines','Telugu', 'Disney+',4,false,52,1,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (56,'Thailand','Bosnian', 'Paramount+',2,true,23,94,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (57,'Bulgaria','Gagauz', 'Paramount+',4,true,84,43,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (58,'Cambodia','Pashto', 'Paramount+',2,false,73,59,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (59,'Brazil','Papiamento', 'Paramount+',3,true,50,78,34);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (60,'Kiribati','Sotho', 'Paramount+',2,true,34,24,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (61,'Indonesia','Dzongkha', 'Paramount+',3,false,34,92,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (62,'Indonesia','Guaraní', 'Paramount+',5,false,67,1,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (63,'Peru','French', 'Paramount+',2,true,38,52,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (64,'France','Zulu', 'Paramount+',3,true,34,27,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (65,'Indonesia','Afrikaans', 'Paramount+',1,false,44,69,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (66,'Indonesia','Maltese', 'Paramount+',5,false,22,97,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (67,'China','Spanish', 'Paramount+',5,false,21,38,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (68,'China','Kyrgyz', 'Paramount+',3,false,36,36,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (69,'Vietnam','Pashto', 'Paramount+',3,false,50,15,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (70,'Portugal','Malay', 'Paramount+',5,true,14,73,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (71,'Brazil','Danish', 'Paramount+',3,true,73,24,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (72,'China','Nepali', 'Paramount+',1,false,26,72,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (73,'China','Tswana', 'Paramount+',5,false,16,3,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (74,'Croatia','Malay', 'Paramount+',2,true,77,57,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (75,'Thailand','Latvian', 'Paramount+',4,true,46,40,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (76,'China','Hebrew', 'Paramount+',3,false,84,74,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (77,'Kazakhstan','Dari', 'Paramount+',5,false,69,30,25);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (78,'Germany','Croatian', 'Paramount+',4,false,48,2,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (79,'Panama','Tamil', 'Paramount+',5,true,65,30,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (80,'Honduras','Hebrew', 'Paramount+',2,false,25,8,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (81,'China','German', 'Paramount+',1,true,20,76,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (82,'Vietnam','Dari', 'Paramount+',1,true,60,74,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (83,'China', 'Spanish', 'Paramount+',1,false,34,52,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (84,'Poland','Afrikaans', 'Paramount+',2,false,55,3,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (85,'Indonesia','Spanish', 'Paramount+',2,true,46,19,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (86,'Greece','Chinese', 'Paramount+',2,false,40,80,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (87,'Philippines','Thai', 'Paramount+',1,true,92,13,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (88,'Canada','Bulgarian', 'Paramount+',1,true,100,42,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (89,'Albania', 'Latvia', 'Paramount+',4,true,11,43,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (90,'Cameroon','Luxembourgish', 'Paramount+',5,true,98,51,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (91,'Indonesia','Albanian', 'Paramount+',5,false,29,74,26);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (92,'Honduras','Italian', 'Paramount+',1,false,8,84,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (93,'Morocco','Tetum', 'Paramount+',2,false,84,56,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (94,'Syria','Hebrew', 'Paramount+',1,false,26,87,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (95,'Tajikistan','Sotho', 'Paramount+',5,true,46,3,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (96,'Philippines','Portuguese', 'Paramount+',1,true,77,1,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (97,'Thailand','Telugu', 'Paramount+',1,true,22,2,66);
insert into review (id, country, language, platform, rating, spoiler_alert, likes, dislikes, content_id) values (98,'China','Thai', 'Paramount+',4,false,34,56,66);